- kale/core.py
- kale/utils/pod_utils.py
- setup.py
- Detect base docker image in case Kale is running in a Kubeflow Notebook server
- Parse `kubectl get pods` output
- Apply current container docker image to every pipeline step
> In cluster inspection to detect docker base image. Closes #6

- kale/codegen/generate_code.py
- kale/core.py
- kale/templates/function_template.txt
- kale/templates/pipeline_template.txt
Whenever a volume is detected over the working dir, use that volume to
marshal data between the steps. When there is no workspace volumes
shared between the steps, fallback to creating a ad-hoc volume for
marshal data mounted at `/marshal`.
Signed-off-by: Stefano Fioravanzo <stefano.fioravanzo@gmail.com>
> Superimpose marshal dir in workspace volume

- kale/rpc/log.py
- kale/rpc/nb.py
- kale/rpc/run.py
* RPC: Add rpc.log.setup_logging()
Remote call setting up loggers
* RPC: Use RPC logger in rpc.nb calls
Use the aforementioned loggers for Kale methods
* RPC: Produce logs during rpc.run.run()
> Setup RPC logging

- kale/rpc/nb.py
We use a logger adapter with logging level set to DEBUG.
Logger adapters don't have handlers, so these lines were producing
errors.
Also we don't need to change logging level, since the exceptions and
errors where introduced in backend and frontend. The log file contains
everything while UI dialogs show a minimal error message.
> RPC/nb: Remove logger manipulation

- kale/rpc/nb.py
This RPC is called directly, that is, without being wrapped by the run()
function, because it needs to run in the same kernel with the open
notebook. Therefore, there isn't a request object to pass.
If we want to log something inside this RPC in the future, then we
should reconsider its arguments.
> RPC/nb: Remove request argument from unmarshal_data

- README.md
Removing pre KubeCon workshop notice that redirected users to the kubecon-workshop branch
> Remove pre-workshop branch notice

- kale/codegen/generate_code.py
- kale/command_line.py
- kale/core.py
- kale/templates/function_template.jinja2
- kale/templates/function_template.txt
- kale/templates/pipeline_template.jinja2
- kale/tests/assets/func01.out.py
- kale/tests/assets/func02.out.py
- kale/tests/assets/func03.out.py
- kale/tests/assets/func04.out.py
- kale/tests/assets/func05.out.py
- kale/tests/assets/func06.out.py
- kale/tests/unit_tests/test_generate_code.py
- kale/tests/unit_tests/test_parser.py
This PR contains 
- a refactoring of the codegen module, basically splitting up the previously monolithic function into multiple smaller and testable functions.
- some polishing of the Jinja templates
- improvements in notebook metadata handling from CLI args to code generation
- fixes here and there to make the gen features work more organically
- unit tests for gen module
> Codegen refactoring and tests

- kale/core.py
- kale/rpc/run.py
- kale/tests/unit_tests/test_metadata_utils.py
- kale/utils/metadata_utils.py
- kale/utils/utils.py
- Move metadata validation from `core` to `utils` module.
- Move some volumes metadata validation from `codegen` to `utils`.
- Add base default metadata dict to standardise fields and values
- Add tests for metadata
> Notebook metadata validation

- .github/workflows/pytest.yml
Apparently, the `push` trigger refers just to pushes to local branches, not PRs coming from external repositories. Adding `pull_request` will trigger the workflow on `opened`, `synchronize ` and `reopened` events.
Ref: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
> Run PyTest workflows on default PR events

- kale/core.py
- kale/nbparser/parser.py
- kale/rpc/nb.py
- kale/static_analysis/ast.py
- kale/templates/pipeline_metrics_template.jinja2
- kale/templates/pipeline_template.jinja2
- kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- kale/tests/assets/notebooks/pipeline_parameters_and_metrics.ipynb
- kale/tests/e2e/test_e2e.py
- kale/tests/unit_tests/test_ast.py
- kale/tests/unit_tests/test_parser.py
- kale/tests/unit_tests/test_rpc_nb.py
This PR add the following functionalities:
- Parse `pipeline-metrics` tag
- Parse and validate code blocks belonging to `pipeline-metrics` tag
- Generate code to run pipeline with pipeline metrics
- RPC to let the UI get the current pipeline metrics
> Support pipeline metrics

- kale/codegen/generate_code.py
- kale/core.py
- kale/nbparser/parser.py
- kale/static_analysis/ast.py
- kale/static_analysis/dependencies.py
- kale/templates/function_template.jinja2
- kale/templates/pipeline_template.jinja2
- kale/tests/assets/functions/func01.out.py
- kale/tests/assets/functions/func02.out.py
- kale/tests/assets/functions/func03.out.py
- kale/tests/assets/functions/func04.out.py
- kale/tests/assets/functions/func05.out.py
- kale/tests/assets/functions/func06.out.py
- kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- kale/tests/assets/kfp_dsl/titanic.py
- kale/tests/assets/notebooks/pipeline_parameters_and_metrics.ipynb
- kale/tests/unit_tests/test_generate_code.py
- kale/tests/unit_tests/test_jupyter_utils.py
- kale/tests/unit_tests/test_utils.py
- kale/utils/jupyter_utils.py
- kale/utils/pod_utils.py
- kale/utils/utils.py
- setup.py
This PR introduces the following changes:
1. Step's code is handles as a list of code blocks, to keep information about the original notebook code cells
2. Utils to create an ipython kernel on the fly and run some code in it, while monitoring for stdout, stderr and error and redirecting the to the main thread.
3. Utils to parse the rich outputs produced by (2) and parse them to create a single html artifact for each execution
4. Extension to the code generation module to generate a pipeline that takes advantage of (1) (2) and (3)
> Run code inside an IPython kernel and capture artifacts

- kale/marshal/utils.py
- kale/templates/function_template.jinja2
- kale/tests/assets/functions/func04.out.py
- kale/tests/assets/functions/func05.out.py
- kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- kale/tests/assets/kfp_dsl/titanic.py
This PR introduces a refactoring of the code that marshals data in and out of pipeline steps.
Instead of producing a lot code using templating, the marshalling code is mode to `marshal/utils.py`, thus making the generated code much simpler.
> Simplify marshal code in templates

- kale/core.py
- kale/nbparser/parser.py
- kale/static_analysis/ast.py
- kale/static_analysis/dependencies.py
- kale/tests/unit_tests/test_ast.py
- kale/tests/unit_tests/test_dependencies.py
- kale/tests/unit_tests/test_graph_utils.py
- kale/utils/graph_utils.py
- setup.py
The previous dependencies detection algorithm (roughly) worked as follows:
1. Get all the "names" of every pipeline step, using static analysis. This includes variable names, function names, import names.
2. Detect `ins` (objects to be loaded) for every step: run pyflakes over the source code of each step to detect which variables are missing.
3. Detect `outs` (objects to be saved) for every step: The outs of a specific step are computed as the intersection between the `ins` of all its childs and the "names" computed during 1. This was done following a reversed topological order of the graph.
The design explained above had many uncovered edge cases and could not be easily extended to future improvements.
This PR introduced a completely revamped approach that can be summarised as follows: …
> New dependencies detection algorithm

- kale/marshal/backends.py
This PR does not add any functionality. Functions were already marshalled correctly using the fallback resource load and save functions. With this PR we have a specific message, so that functions are not treated as 'general objects' but properly as functions.
> Add backends to marshal functions

- kale/templates/function_template.jinja2
- kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
---
The problem is that `pipeline_metrics` special step is adding the HTML output (empty) in `mlpipeline-ui-metadata` but in the same time it is not set as an output artifact (so it's not uploaded in artifact store). Thus, KFP UI produces an error when trying to fetch it.
I'm not sure if that's the best way to write the template, without it being complex. Feel free to propose a different format!
> Fix pipeline-metrics to not include html in ui-metadata

- kale/command_line.py
- kale/rpc/kfp.py
- kale/templates/pipeline_template.jinja2
- kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- kale/tests/assets/kfp_dsl/titanic.py
- kale/utils/kfp_utils.py
* Provide a kfp_utils.generate_run_name() function which accepts a
pipeline name (str) and generates a _unique_ run name.
* Use that function everywhere across the repo for a uniform experience.
> Generate unique run names uniformly across repo

- kale/core.py
- kale/rpc/nb.py
Alongside adding a simple function to `rpc/nb.py` to perform validation of the notebook before taking the volume stapshots, this PR includes:
- Refactoring of the logging logic, by moving the initialisation of the main Kale logger from `Kale.__init__()` to `kale/__init__.py`.
- Remove the snapshot procedure at the end of `Kale.__init__()`. Since now we always take snapshots from the UI, using the rpcs defined in `rpc/rok.py` we were execution code with no effect. It makes sense to remove the snapshotting logic from `__init__` anyway and, in case we would like to be able to take snapshots by running Kale from CLI in the future, then we will probably repurpose the functions defined in `rpc/rok.py`.
@elikatsis one note: by moving the initialisation of the logger to `__init__.py` and getting …
> Add a new RPC to validate notebook metadata

- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
- backend/kale/tests/assets/notebooks/pipeline_parameters_and_metrics.ipynb
- backend/kale/utils/metadata_utils.py
- labextension/src/components/ExperimentInput.tsx
Since we will use the KFP experiment name as the Katib experiment name and since Katib requires a valid K8s resource name for the experiment, we need to validate the KFP experiment name accordingly. This does not hamper much usability, as the use can still still create names that are expressive enough.
> Restrict experiment name to be a valid k8s name

- backend/kale/tests/unit_tests/test_jupyter_utils.py
- backend/kale/utils/jupyter_utils.py
This PR adds the text streams `stdout` and `stderr` to the notebook artifact that is generated for each pipeline step. In this way, the artifact tries to be a as close as possible replica of the original output seen in the notebook.
> backend: Add text streams to the notebook's KFP artifact

- backend/kale/nbparser/parser.py
- backend/kale/templates/pipeline_template.jinja2
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/notebooks/pipeline_parameters_and_metrics.ipynb
- labextension/src/components/cell-metadata/CellMetadataEditor.tsx
- labextension/src/components/cell-metadata/CellMetadataEditorDialog.tsx
- labextension/src/components/cell-metadata/InlineCellMetadata.tsx
- labextension/src/components/cell-metadata/InlineMetadata.tsx
- labextension/src/utils/TagsUtils.ts
This PR adds two new tags to the backend: `annotation` and `limit`. These tags are parsed in `step` cells and are added respectively as pod annotations and K8s resource limits using the KFP SDK.
On the UI side, the PR adds a new Dialog to request the use of GPU for a specific pipeline step.
> Add annotation and limit tags and GPU UI

- backend/kale/core.py
- backend/kale/templates/function_template.jinja2
- backend/kale/tests/assets/functions/func03.out.py
- backend/kale/utils/graph_utils.py
- backend/kale/utils/pod_utils.py
* Take Rok auto snapshot after step's execution too
* Take a single snapshot during final auto-snapshot step
* Fix get_leaf_nodes()
get_leaf_nodes used to return all leaf nodes that have at least one
parent. However, a node should be considered as leaf even if it is not
dependent to any other step. This commit fixes that behavior.
* Add final snapshot step only if multiple DAG leaves
> Change auto-snapshot behavior

- labextension/src/components/cell-metadata/InlineMetadata.tsx
Since special tags are treated as block names, when setting a special
tag to a cell that already has some metadata (e.g. `prev` tags) the only
one that is removed is the previous `block:***` tag.
This commit prevents cells tagged with reserved tags to show inline
metadata information coming from other tags. This is just a workaround
for now, as the end goal will be to treat differently step names from
special tags.
> labextension: Show just tag name for reserved tags

- labextension/src/components/Components.tsx
- labextension/src/components/KatibDialog.tsx
- labextension/style/index.css
Katib support categorical arguments (i.e. lists of values) or numeric
arguments (int, double) defined in terms of `min`, `max` and `step`. It
is often the case that we need to run HP Tuning with a numeric arg that
has a list of choices (e.g. 0.0001, 0.001, 0.1) not expressible as a
range.
We allow changing the default range spec of numeric pipeline args to
categorical. This works because KFP converts all the pipeline args
from string to their annotated type.
There could be unintended side effects in how Katib's optimization
algorithms handle categorical differently from range. For that we
inform the user when making this choice.
> labextension: Add lists to numeric Katib args

- backend/kale/core.py
- backend/kale/rpc/katib.py
- backend/kale/tests/unit_tests/test_rpc_katib.py
- backend/kale/utils/kfp_utils.py
- labextension/src/components/LeftPanelWidget.tsx
Since (most) RPCs are called from a separate kernel, they have a base path different from the notebook (usually `$HOME`).
This PR is a fix so that all compiled artifacts (KFP DSL, Argo workflow definition and Katib experiment definition) are saved next to the `ipynb` file.
[It also changes the Argo workflow compiled file to a YAML instead of a gzipped tarball for UX purposes]
> Fix compiled artifact save paths

- labextension/src/lib/NotebookUtils.tsx
- labextension/src/widgets/LeftPanelWidget.tsx
- labextension/src/widgets/cell-metadata/InlineCellMetadata.tsx
This commits changes how the extension tracks the currently active
notebook cell. Tracking this information is needed because we are
showing just one cell metadata editor at any given time.
Since the beginning, this information was tracked in the state of the
LeftPanelWidget component and was then passed down to the InlineMetadata
component. Since the LeftPanelWidget just acted as a tracker, without
actively using this information, now the tracking is moved to
InlineMetadata so that there is no useless state passing.
In this way, many functions inside LeftPanelWidget are freed from having
to set the state, and can now be refactore more easily.
> labextension: Improve active cell tracking

- labextension/src/components/AnnotationInput.tsx
- labextension/src/components/ExperimentInput.tsx
- labextension/src/components/Select.tsx
- labextension/src/lib/Commands.ts
- labextension/src/widgets/KatibDialog.tsx
- labextension/src/widgets/LeftPanelWidget.tsx
- labextension/src/widgets/VolumesPanel.tsx
This PR moved all the RPC commands (and their related auxiliary logics) to a separate Command class. This is just a first iteration to make the LeftPanelWidget a lighter component. In the future, further refactoring will be done on the Commands functions themselves to improve their logic and maintainability.
> labextension: Reorganise RPC commands

- backend/kale/templates/pipeline_template.jinja2
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
volume_name_parameters list gets the parameter names before
sanitization. However, the compiler sanitizes step names. This results in
inconsistency between the two.
This commit fixes this inconsistency.
> Fix marshal volume creation step name

- backend/kale/rpc/kfp.py
kfp_client.list_experiments() returns {..., experiments: None} when no
experiments are found, so the iteration raises an error.
This commit fixes the behavior.
> rpc/kfp: Fix NoneType error in list_experiments()

- backend/kale/marshal/backends.py
The only Pandas objects that expose a `to_pickle` functions are
`pandas.core.frame.DataFrame` and `pandas.core.series.Series`. This
commit fixes the Pandas backend marshalling regex to catch just these
two type and not all `pandas.*` types. Any other Pandas object will
fallback to using `dill`.
> backend: Fix wrong regex for Pandas marshalling

- backend/kale/rpc/kfp.py
This commit implements a minor workaround for [1] until we ship images
with KFP SDK containing its fix.
[1]: https://github.com/kubeflow/pipelines/issues/4176
> kfp: Work around get_experiment() issue

- backend/kale/marshal/__init__.py
- backend/kale/marshal/utils.py
- backend/kale/templates/function_template.jinja2
- backend/kale/tests/assets/functions/func04.out.py
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
- backend/kale/utils/jupyter_utils.py
- backend/kale/utils/log_utils.py
- backend/kale/utils/utils.py
Improve the logging in the marshal module to show clean and easy to
unrstand error messages in case Kale fails to marshal an object.
The traceback of the produced error is not shows to stdout but logged in
kale.log
> logging: Improve logs in the marshal module

- backend/kale/utils/jupyter_utils.py
- backend/kale/utils/log_utils.py
Using a standard logger it's not possible to just print empty lines
without having to print the Formatter prefix as well. This can be a
limitation when we want to use just the logger for user-facing outputs,
but we also want to be able to space out some section, producing empty
lines.
This commit extends the base Logger class with a funtion that, when
called, temporarily suppress all the handlers' formatters with the empty
string, logs empty lines, and then restored the original formatters.
NOTE: This function is not thread safe. If multiple processes are using
the same logger concurrently, there might be cases when one thread uses
the logger while its formatters are being suppressed by another thread.
Current Kale is not multithreaded, so this is not an issue.
Signed-off-by: Stefano …
> logging: custom logger for printing empty lines

- backend/kale/core.py
- backend/kale/rpc/nb.py
- labextension/src/widget.tsx
- labextension/src/widgets/KatibDialog.tsx
- labextension/src/widgets/LeftPanelWidget.tsx
Jupyterlab can be started with the `--notebook-dir` CLI argument. The
spceified dir will effectively become the root path visible from the JP
UI. This could be useful if one wants to start the Jupyter server in the
home folder, but wants to give access to the user just to a subfolder.
Until now Kale was assuming that the jupyter process was running in the
HOME directory, without `--notebook-dir`. When this assumption does not
hold anymore, Kale cannot find the notebook anymore, since we use a
relative path.
This commit retrieves the "server root" path (i.e. the absolute path to
`--notebook-dir`) and uses it to always point to the notebook with an
abolute path.
NOTE: `PageConfig.getOption('serverRoot')` returns a path where the HOME
prefix is `~`. We handle this in the backend by expanding …
> Support Jupyter notebook-dir CLI argument

- backend/kale/common/kfutils.py
- backend/kale/common/metadatautils.py
- backend/kale/core.py
- backend/kale/nbparser/parser.py
- backend/kale/rpc/nb.py
- backend/kale/templates/pipeline_template.jinja2
- labextension/src/lib/Commands.ts
- labextension/src/widgets/LeftPanel.tsx
In this PR the main focus is to retrieve PodDefaults applied on the notebook server and pass them on to pipeline steps.
To achieve this we:
* first add support to add labels on steps via cell tags,
* then we introduce a new field in metadata allowing global configurations for steps (currently annotations, labels, limits)
[these configurations may be overwritten by cell-specific tags],
* then we add utils and an RPC to list and filter PodDefaults (according to our needs aka PodDefaults applied on pod) as well as fetch the labels required for these PodDefaults to be applied,
* and, finally, we let the lab extension orchestrate all the above
> Apply notebook server's PodDefaults on pipeline steps

- backend/kale/core.py
- backend/kale/nbparser/parser.py
We weren't adding the `step_defaults` configurations to the final auto-snapshot step.
This PR fixes that behavior.
The PR also contains a small performance fix: we were parsing the `step_defaults` property again and again, instead of just once.
> backend: Fix auto-snapshot step wrt step defaults

- backend/kale/rpc/katib.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
* Add label for PodDefault to be applied
* Specify service account for the trial
* Bump image
**TODO:** Create & use new image after merging
---
[Depends on #178]
> backend: Allow Katib trials to access KFP

- backend/kale/marshal/backends.py
- backend/kale/marshal/utils.py
To support the tf.keras model serialization a new backend is added
to save the mode in the SavedModel format. This produces a folder
instead of a single file. Thus, utils.py file is also altered to
see folders as serialized objects in the case of TensorFlow artifacts.
The choise to proceed with SavedModel format instead of a single .h5 file
was taken because SavedModel is the new standard as of TF 2.x.
Later, we can use this format as is to deploy models as web services,
to edge devices or TensorFlow JS.
> marshal: Support tf.keras model serialization

- backend/kale/marshal/utils.py
Produce a friendly message in case Kale tries to load a file/folder at
the beginning of the step, but the file does not exist.
> backend: Improve marshal log when file is missing

- backend/kale/codegen/generate_code.py
- backend/kale/templates/function_template.jinja2
- backend/kale/templates/pipeline_template.jinja2
- backend/kale/tests/assets/functions/func04.out.py
- backend/kale/tests/assets/functions/func05.out.py
- backend/kale/tests/assets/functions/func06.out.py
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
In case a pipeline parameter had the same name as one of the variables
used by Kale in the `dsl.pipeline` decorated function, the value of the
pipeline parameter would be overwritten.
This commit prevents this by obfuscating all the local variables
assigned and used by Kale.
> backend: Obfuscate template var names used by Kale

- labextension/src/lib/NotebookUtils.tsx
* Don't run the 'pipeline-metrics' cell
* Don't miss a cell when breaking the inner while loop
> labextension: Fix runGlobalCells() method

- backend/kale/marshal/backends.py
The model will load in inference mode and won't be ready for further training.
If the user wants to train it further he would have to compile it again.
However, this is preferable in order to support custom loss functions and optimizers.
For example, if the user has trained a model with a custom loss function
or a custom optimizer and tries to load it with compile set to True
a `ValueError` will occur specifying that it does not recognize this loss function
or optimizer. Thus the step will fail on KFP.
> marshal: Set compile to False when loading the model

- backend/kale/common/kfputils.py
Upon KFP Run creation, submit a patch to the Katib Trial adding an
annotation which contains the UUID of the KFP Run
> backend: Associate Katib Trial with KFP Run

- backend/kale/marshal/backends.py
TensorFlow serving expects a model to saved under a versioned (e.g. 1/,
2/, ...) folder, so that the user can save multiple versions of the same
mudel in the same place.
We now always save a model under `1/` just in case the dump needs to be
served as well. The function `load_model` does not handle this case
thouth, so we need to take it into account.
> marshal: Save TF models under a versioned folder

- backend/kale/marshal/backends.py
Change the type marching from `keras*` to `keras.*` for the Keras
backend to use stand pickling for objects likes
`keras_preprocessing.text.Tokenizers`.
> marshal: Restrict types for Keras backend

- labextension/src/lib/Utils.ts
- labextension/src/widgets/deploys-progress/KatibProgress.tsx
We need to handle Katib UI serving in multiple URLs. With this new
component (KatibExperimentLink) we test the supported Katib UIs, choose
the one that responds successfully, and render using it in an
asynchronous and clean way.
> labextension: Support serving Katib in different locations

- labextension/src/widgets/LeftPanel.tsx
We have been calling setState() multiple times while also using the
current state. We were bumping into issues with incorrect update values
and we found out we were doing the wrong thing mentioned in [1].
This commit fixes all setState() calls that belong in this category.
[1] https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous
> labextension: Fix setState() calls when referencing the current state

- backend/kale/marshal/backends.py
This commit adds support for serializing XGBoost DMatrix and Booster objects.
DMatrix is an internal data structure, which is optimized for both memory
efficiency and training speed. It is not pickle-able so we should use its
own  method. On the other hand, Booster, which is an XGBoost
model is pickle-able, but it's better to use its native method.
Similarly, we can use the corresponding load methods to load a DMatrix or
Booster object.
> marshal: Add support for XGBoost

- labextension/src/widgets/KatibDialog.tsx
This commit temporarily disables Hyperband and TPE due to bad configuration. We will address the issue again when upgrading to Katib `v1beta1`.
> labextension: Disable misconfigured Katib algorithms

- examples/openvaccine-kaggle-competition/open-vaccine.ipynb
Running more that one pipeline concurrently in MiniKF considerably slows
down the VM.
> examples: Limit parallel HPT runs in OpenVaccine

- backend/kale/cli.py
- backend/kale/config/config.py
- backend/kale/config/validators.py
- backend/kale/pipeline.py
- backend/kale/templates/pipeline_template.jinja2
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
- labextension/src/components/Input.tsx
- labextension/src/components/VolumeAccessModeSelect.tsx
- labextension/src/widgets/LeftPanel.tsx
- labextension/src/widgets/VolumesPanel.tsx
This PR adds the following two features:
* Specify storage class for the created PVCs
* Specify the access modes for the creates PVCs
It also extends the Kale CLI as well as the lab extensions to set these options.
**Note:** This PR, allows both a global and a per-PVC configuration for the above, giving priority to the per-PVC one. However, the per-PVC configuration is not available through the lab extension because it looks like it just complicates things.
Closes #51
Closes #161
Closes #207
> Enable specifying the storage class and access modes of the created PVCs

- labextension/src/widget.tsx
- labextension/style/index.css
JupyterLab reduced the minimum with of the sidebar from to 180px; the
proper way to override this setting is to create a new theme. Since
Kale does not make use of a custom theme, the quickest way to override
the panel's setting is to add a CSS class to it from the widget object.
> labextension: Set min width of Kale panel to 300px

- examples/openvaccine-kaggle-competition/open-vaccine.ipynb
Fix a couple of typos in the OpenVaccine notebook
> Fix a couple of typos

- .github/workflows/ci-workflow.yml
- backend/kale/common/k8sutils.py
- backend/setup.py
With the new dependency resolver introduced in pip 20.3, dependency
resolution would get stuck because of the following conflicts:
1. `kfserving` requires `kubernetes==10.0.1`
2. Kale's `setup.py` specifies `kubernetes>=11.0.0`
We introduced (2) in [1]. This commit reverts that change and manually
catches the `TypeError` exception.
`kfserving` version 0.5.0 changes the `kubernetes` requirement to
install versions >=12.0.0. However, this is incompatible with KFP
requirement (<12.0.0).
This is also incompatible with our code, since in version 12.0.0 there
are breaking changes on code we import (e.g., Exceptions).
As a result, we change the restrictions as follows:
* `kfserving >= 0.4.0, < 0.5.0`
* `kubernetes < 12.0.0`
Closes https://github.com/kubeflow-kale/kale/issues/273
Closes …
> backend: Fix pip 20.3 dependency resolution

- docker/jupyterlab/Dockerfile
- docker/jupyterlab/Dockerfile.dev
- docker/jupyterlab/Dockerfile.rok
- docker/jupyterlab/Dockerfile.rok.dev
* Force the installation of enum34==1.1.8. Other versions raise errors
on KFP installation
* Do not install KFP separately, let Kale requirements do it
Closes https://github.com/kubeflow-kale/kale/issues/274
> docker: Fix Dockerfiles (enum & KFP installation)

- .vscode/settings.json
- backend/kale/common/podutils.py
Part of https://github.com/kubeflow-kale/kale/pull/217/files
This code adds the functionality to check if a snapshot provisioner exists in the cluster, and if the storage provider of the PVCs for the notebook have a snapshot class associated with them. Additionally, the check that restricted using snapshots to `ROK_CSI_STORAGE_CLASS` has been expanded for the previously mentioned checks.
> (Backend): Check if snapshots are available for notebook pvcs

- backend/kale/common/podutils.py
- backend/kale/pipeline.py
This PR improves the detection of the base docker image being used by the Pod, retrieving the image SHA (when available).
This ensures that reproducibility even when the base image has a non-reproducible tag (e.g. `latest`)
> Detect docker image SHA instead of tag

- backend/kale/marshal/backend.py
Lower the log level of the missing backend logs, so users are not
overwhelmed by warnings when a lot of data is passed with the default
backend.
> backend: Make marshal logs less intrusive

- backend/kale/__init__.py
- backend/kale/common/runutils.py
- backend/kale/sdk/__init__.py
- backend/kale/sdk/api.py
- backend/kale/step.py
- backend/kale/templates/pipeline_template.jinja2
- backend/kale/templates/py_function_template.jinja2
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters.py
- backend/kale/tests/assets/kfp_dsl/simple_data_passing.py
- examples/sdk/artifact.py
This PR introduces a new SDK decorator that allows users to declare
the artifacts created during a step execution. The `@artifact` decorator
is thus supposed to be used on functions that have already been
decorated with the `@step` decorator.
Declaring step artifacts must be done before the step actually executes,
because Kale needs to create a pipeline that is aware of these outputs,
and properly update each step's output artifacts dictionary in the KFP
DSL.
Currently only HTML artifacts are supported.
> Create KFP artifacts using the SDK

- backend/kale/common/mlmdutils.py
- backend/setup.py
* Update ML Metadata requirement
* Fix error handling after the upgrade
* Use a client method available in the newer version
* Allow configuring the max length of gRPC messages
> Bump MLMD version

- backend/kale/common/kfputils.py
- backend/kale/compiler.py
- backend/kale/tests/assets/kfp_dsl/iris.py
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/setup.py
The first time you create and upload a pipeline this happens:
```
2025-08-25 15:29:13 Kale kfputils:149         [INFO]     Uploaded Pipeline 'kale-pipeline' id: 3b92a161-2af1-41a4-8ae0-a89ee472ee02
Pipeline details: http://127.0.0.1:8080//#/pipelines/details/3b92a161-2af1-41a4-8ae0-a89ee472ee02/version/5a478f38-8f69-4b20-bfef-9c2bcdb7c0c9
Traceback (most recent call last):
File "/Users/stefano/git/kubeflow-kale/kale/./backend/kale/cli.py", line 123, in <module>
main()
File "/Users/stefano/git/kubeflow-kale/kale/./backend/kale/cli.py", line 106, in main
pipeline_id, version_id = kfputils.upload_pipeline(
File "/Users/stefano/git/kubeflow-kale/kale/backend/kale/common/kfputils.py", line 155, in upload_pipeline
client.delete_pipeline_version(upp.pipeline_id)
TypeError: …
```
> fix(backend): Cleanup pipeline version on first upload
