kubeflow-kale/kale

- kale/templates/pipeline_template.txt
> Use dict for annotations

- kale/codegen/generate_code.py
- kale/core.py
- kale/nbparser/parser.py
- kale/static_analysis/dep_analysis.py
- kale/static_analysis/inspector.py
- kale/templates/function_template.txt
- kale/templates/pipeline_template.txt
Add support for a new cell type `pipeline-parameters` that will trigger the generation of pipeline parameters in DSL
> Pipeline parameters

- kale/codegen/generate_code.py
- kale/templates/pipeline_template.txt
> Support multiple volume annotations

- kale/nb_utils.py
Add a module with notebook related helpers that allow retrieving the namespace the notebook is running in, and listing its mounted volumes.
> Add module with notebook helpers

- kale/codegen/generate_code.py
- kale/core.py
- kale/templates/pipeline_template.txt
> Set containers working directory as Notebook directory absolute path

- kale/codegen/generate_code.py
- kale/templates/function_template.txt
- kale/templates/pipeline_template.txt
Whenever possible, remove marshal volume in favor of a folder placed in the workspace volume
> Remove marshal volume

- README.md
- kale/codegen/generate_code.py
- kale/core.py
- kale/nbparser/parser.py
- kale/templates/function_template.txt
- kale/templates/pipeline_template.txt
- kale/utils/pod_utils.py
This PR contains changes in preparation for features introduced in KubeCon workshop, as well as minor fixes.
> Prepare master branch for KubeCon workshop features

- kale/codegen/generate_code.py
- kale/core.py
- kale/templates/pipeline_template.txt
Signed-off-by: Kostis Lolos <klolos@arrikto.com>
> Support cloning existing notebook volumes

- kale/command_line.py
- setup.py
Signed-off-by: Kostis Lolos <klolos@arrikto.com>
> Add CLI kale-volumes -o {table,json} {list}

- kale/rpc/kfp.py
- kale/rpc/nb.py
- kale/rpc/rok.py
- kale/rpc/run.py
- kale/utils/pod_utils.py
- setup.py
* Add `kale.rpc` module
* Add `rpc.kfp` module
* Add `rpc.nb` module
* Add `rpc.rok` module
> Add kale.rpc module and submodules

- kale/rpc/nb.py
> Support notebook path instead of filename when recovering

- kale/rpc/errors.py
- kale/rpc/run.py
- kale/rpc/utils.py
* Rename `Status` -> `Code`
* Move `errors` to a dedicated module
* Implement RPC Exceptions
> Introduce RPC Exceptions

- kale/rpc/rok.py
> RPC: Add rpc.rok.check_rok_availability()

- kale/core.py
- kale/rpc/errors.py
- kale/rpc/kfp.py
- kale/rpc/log.py
- kale/rpc/nb.py
- kale/rpc/rok.py
- kale/rpc/run.py
* Setup distinct root & `kale.rpc` loggers
* Setup RPC request object
This object contains all the RPC context (transaction ID, notebook path, and a logger adapter with this information set in the format string)
* Pass trans_id in RPC response
Return transaction ID to the frontend so it can be shown/logged
> Upgrade logging feature

- kale/utils/pod_utils.py
> Return actual run UUID if it's annotated to the workflow

- .github/workflows/pytest.yml
The workflow will run at every commit (to any branch or PR). We could restrict this to run only during PR or commits to mater, but since it is inexpensive on our part and the task is relatively quick we can leave like this.
> Add PyTest workflow

- docker/jupyterlab/Dockerfile
- docker/jupyterlab/Dockerfile.dev
- docker/jupyterlab/Dockerfile.rok
- docker/jupyterlab/Dockerfile.rok.dev
Use `pip install -U` in Dockerfiles when installing kale.
This force-updates kale requirements that are not satisfied.
> Dockerfiles: Force-update unsatisfied kale requirements

- kale/rpc/kfp.py
> Fix RPC run_pipeline to accept pipeline_id

- kale/codegen/generate_code.py
- kale/core.py
- kale/static_analysis/dependencies.py
- kale/templates/function_template.jinja2
- kale/templates/pipeline_template.jinja2
- kale/tests/assets/functions/func02.out.py
- kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- kale/tests/unit_tests/test_generate_code.py
This PR restricts the number of pipeline parameters that are passed to the lightweight functions to those that are actually needed by each pipeline step.
> Pass appropriate pipeline parameters to pipeline steps

- kale/codegen/generate_code.py
- kale/tests/assets/kfp_dsl/titanic.py
We need to escape characters like `\n`, `\r` etc from the source code, otherwise they are parsed as escape characters by ipython and they screw up the executed source code.
This solution is just a proposal, open for discussion.
> Escape characters with unicode_escape encode

- .flake8
- kale/command_line.py
- kale/core.py
- kale/marshal/__init__.py
- kale/marshal/backends.py
- kale/marshal/dispatchers.py
- kale/marshal/resource_load.py
- kale/marshal/resource_save.py
- kale/marshal/utils.py
- kale/rpc/errors.py
- kale/rpc/kfp.py
- kale/rpc/log.py
- kale/rpc/nb.py
- kale/rpc/rok.py
- kale/rpc/run.py
- kale/rpc/utils.py
- kale/static_analysis/dependencies.py
- kale/tests/unit_tests/test_generate_code.py
- kale/tests/unit_tests/test_metadata_utils.py
- kale/tests/unit_tests/test_rpc_nb.py
- kale/utils/jupyter_utils.py
- kale/utils/kfp_utils.py
- kale/utils/metadata_utils.py
- kale/utils/pod_utils.py
- setup.py
Opening this PR as WIP. The current objective is to make the command `flake8 --docstring-convention google --exclude assets --ignore=D107,D100,D104,W503 kale` pass without errors or warnings.
> Clean Up Codebase

- kale/static_analysis/ast.py
- kale/static_analysis/dependencies.py
- kale/tests/unit_tests/test_ast.py
- kale/tests/unit_tests/test_dependencies.py
This PR introduces the following changes:
- In commit 6ddffd6 we fix a regression introduce in #81 
- Afterwards, we implement an improvement in the detection of data dependencies, in the context of functions with free variables.
> Improve dependencies detection algorithm

- .github/workflows/ci-workflow.yml
> Limit workflow execution: all PRs & push to master branch only

- kale/marshal/__init__.py
- kale/marshal/backends.py
- kale/marshal/resource_load.py
- kale/marshal/resource_save.py
> Use logging to print messages in marshal module

- kale/utils/kfp_utils.py
- kale/utils/pod_utils.py
- kale/utils/utils.py
* Add RunID in Rok snapshot metadata
* Put snapshots in buckets named after the experiment the run belongs in
> Auto-snapshot: Enhance UX

- setup.py
> Pin upper versions for kfp and nbconvert

- backend/kale/rpc/katib.py
- backend/kale/rpc/kfp.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
- backend/kale/tests/unit_tests/test_rpc_katib.py
- backend/kale/utils/kfp_utils.py
- backend/kale/utils/metadata_utils.py
- backend/kale/utils/utils.py
- docker/katib/Dockerfile
- docker/katib/Dockerfile.dev
This PR introduces new RPCs to create and monitor Katib Experiments.
> backend: Add RPCs and helpers to manage Katib experiments

- backend/kale/utils/metadata_utils.py
> Relax experiment name validation for simple runs

- labextension/src/components/DeployButton.tsx
> labextension: highlight circular progress

- backend/kale/tests/assets/functions/func07.out.py
- backend/kale/tests/unit_tests/test_generate_code.py
> Add unit test for #111

- backend/kale/core.py
- backend/kale/marshal/__init__.py
- backend/kale/rpc/log.py
- backend/kale/tests/e2e/test_e2e.py
- backend/kale/utils/__init__.py
- backend/kale/utils/log_utils.py
- backend/kale/utils/pod_utils.py
* Introduce log_utils module
* marshal: Replace setup_logging with custom get_logger util
* utils: Initialize logger
* pod_utils: Use proper logger
* Fix RPC logger propagate value (use bool)
* pod_utils: Mark start & end of snapshotting logs
> Revamp setting up loggers

- README.md
> Add dev guide

- backend/kale/rpc/katib.py
- labextension/package.json
- labextension/src/lib/NotebookUtils.tsx
- labextension/src/widgets/deploys-progress/DeployProgress.tsx
- labextension/style/index.css
- labextension/yarn.lock
* Add dialog-body CSS class for notebook dialogs
* Introduce InfoBadge
* Return and show `currentOptimalTrial` field of Katib experiment's status
> Katib progress: Show current optimal trial

- backend/setup.py
> Specify upper bound for ml_metadata module version

- backend/kale/templates/pipeline_template.jinja2
> backend: Fix add_pod_annotation() call used on container instead of step

- backend/kale/templates/pipeline_template.jinja2
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
> mlmd: Add label to exclude Kale pods from MetadataWriter

- examples/dog-breed-classification/dog-breed-katib.ipynb
- Add feasible space for `learning_rate`
- Skip the requirements cell
Signed-off-by: Christos S. Pavlou <cspavlou@arrikto.com>
> Fix the Katib notebook

- backend/kale/rpc/katib.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
> backend: Switch to public Katib KFP trial image

- backend/kale/rpc/katib.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
> Use a lightweight image for the Katib KFP trial

- README.md
- backend/setup.py
- docker/jupyterlab/Dockerfile
- docker/jupyterlab/Dockerfile.rok
- examples/base/candies_sharing.ipynb
- labextension/package.json
> Version bump to 0.5

- backend/kale/utils/mlmd_utils.py
> mlmd_utils: Fix bug in default value of annotation

- labextension/src/lib/NotebookUtils.tsx
> labextension: Add 'Dismiss' button in refresh dialogs

- backend/kale/utils/mlmd_utils.py
> mlmd: Catch race if two steps attempt to create context concurrently

- labextension/package.json
- labextension/src/components/AdvancedSettings.tsx
- labextension/src/components/Input.tsx
- labextension/src/lib/CellUtils.ts
- labextension/src/lib/Commands.ts
- labextension/src/lib/NotebookUtils.tsx
- labextension/src/lib/RPCUtils.tsx
- labextension/src/widget.tsx
- labextension/src/widgets/KatibDialog.tsx
- labextension/src/widgets/LeftPanelWidget.tsx
- labextension/tsconfig.json
- labextension/yarn.lock
A list of required changes can be found here:
https://jupyterlab.readthedocs.io/en/latest/developer/extension_migration.html
Signed-off-by: DavidSpek <vanderspek.david@gmail.com>
> labextension: update to JupyterLab 2.x

- backend/kale/utils/log_utils.py
> logging: make log records vertically aligned

- labextension/src/widgets/VolumesPanel.tsx
> labextension: Fix autosnapshot switch label

- backend/kale/common/logutils.py
> backend: add date to logger stream handler

- backend/kale/rpc/katib.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
> rpc/katib: Update Katib trial image

- examples/dog-breed-classification/requirements/requirements-v2.txt
The dog breed example has updated code to support Tensorflow 2.3.0.
> examples: Add support for TensorFlow 2.x

- backend/setup.py
- labextension/package.json
> Release version 0.5.1

- backend/setup.py
> Change to ml_metadata 0.24.0

- backend/kale/rpc/katib.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
This image contains the feature implemented in 2fb4eeb
> rpc/katib: Update Trials image

- backend/kale/common/podutils.py
Improve detection of the current container in case we are not 
running inside a notebook pod.
> backend: Improve detection of the container name

- backend/kale/common/podutils.py
- backend/kale/rpc/nb.py
- backend/kale/tests/unit_tests/test_podutils.py
This function returns the PVC that container the input absolute path.
Add an RPC as well.
> backend: Get PVC from path

- backend/kale/common/podutils.py
- backend/kale/common/rokutils.py
- backend/kale/templates/function_template.jinja2
- backend/kale/tests/assets/functions/func03.out.py
- backend/kale/tests/assets/functions/func07.out.py
* Add some new functions
* Refactor old functions from podutils to rokutils
* Refactor logging and other logic
> Improve Rokutils

- backend/kale/common/jputils.py
- backend/setup.py
> backend: get the name of active notebook

- backend/kale/common/kfputils.py
- backend/kale/common/mlmdutils.py
- backend/kale/common/rokutils.py
- backend/kale/common/utils.py
- backend/kale/rpc/nb.py
- labextension/src/lib/Commands.ts
* Generate a visualization
* Add state metadata to the snapshot
* Handle recovering when using a final snapshot
Minor extra:
* Fix RokSnapshot artifact URIs
> Improve the final Rok snapshot handling

- backend/kale/common/mlmdutils.py
> backend/mlmd: Format KFP run ID as a URI

- backend/kale/common/katibutils.py
- backend/kale/common/kfputils.py
- backend/kale/common/podutils.py
- backend/kale/common/workflowutils.py
In continuation of https://github.com/kubeflow-kale/kale/pull/223, we also annotate the workflow with Katib details to maintain the association.
> backend: Annotate workflows corresponding to Trials with Katib details

- backend/kale/common/k8sutils.py
- backend/kale/common/katibutils.py
- backend/kale/common/kfputils.py
- backend/kale/common/kfutils.py
- backend/kale/common/mlmdutils.py
- backend/kale/common/podutils.py
- backend/kale/common/rokutils.py
- backend/kale/common/workflowutils.py
- backend/kale/pipeline.py
- backend/kale/rpc/katib.py
> backend: Introduce k8sutils

- backend/kale/rpc/katib.py
- backend/kale/tests/assets/yamls/katib-experiment.yaml
- backend/kale/tests/unit_tests/test_rpc_katib.py
> backend: Update Katib trial image

- examples/openvaccine-kaggle-competition/open-vaccine.ipynb
> examples: Get validation loss from array

- FAQ.md
- README.md
- docker/jupyterlab/Dockerfile
- docker/jupyterlab/Dockerfile.dev
- docker/jupyterlab/Dockerfile.rok
- docker/jupyterlab/Dockerfile.rok.dev
* Update references to `jupyterlab` versions
* Add section in FAQ for KFP compiler errors
Closes #234 
Closes #246
> chore: Update documentation related files

- backend/kale/rpc/kfp.py
> backend/rpc: Initialize KFP client on each use

- backend/kale/common/kfputils.py
- backend/kale/common/utils.py
- backend/kale/templates/pipeline_template.jinja2
- backend/kale/tests/assets/kfp_dsl/pipeline_parameters_and_metrics.py
- backend/kale/tests/assets/kfp_dsl/titanic.py
> backend: Move step generated artifacts under /tmp

- examples/openvaccine-kaggle-competition/requirements.txt
> examples: Add TF to the OpenVaccine requirements

- backend/kale/rpc/katib.py
Getting the Katib experiment too soon after its creation may result to
the object not having its status field populated.
This commit ensures the returned experiment has a status field, else
returns a basic response.
> rpc: Ensure the retrieved Experiment has status

- backend/kale/rpc/katib.py
> rpc: Update Katib trial image

- labextension/src/components/AdvancedSettings.tsx
- labextension/src/widgets/LeftPanel.tsx
> labextension: Move volumes panel to advanced sec

- labextension/src/lib/NotebookUtils.tsx
> labextension: Change 'dismiss' button to 'close'

- backend/kale/marshal/backends.py
We use TorchScript to save and load a PyTorch model.
TorchScript works in a similar way to TF's SavedModel.
TorchScript is a way to create serializable and optimizable
models from PyTorch code.
Any TorchScript program can be saved from a Python process
and loaded in a process where there is no Python dependency.
> marshal: Add support for PyTorch models

- backend/kale/common/k8sutils.py
Part of https://github.com/kubeflow-kale/kale/pull/217
This PR adds a function to get the kubernetes storage client to the k8sutils in the backend.
> (Backend): Add k8s storage client to k8sutils

- backend/kale/rpc/katib.py
> katib: Update katib trial image

- backend/kale/common/kfputils.py
- backend/kale/common/mlmdutils.py
- backend/kale/common/podutils.py
- backend/kale/common/rokutils.py
- backend/kale/common/workflowutils.py
- backend/kale/marshal/decorator.py
- backend/setup.py
This PR brings some refactoring and bug fixing to some of our common util modules.
> Various utils improvements
